### ISSUE TITLE
Policy for dependencies of environments

### ISSUE THREAD

**Issue by R-Sweke** [HendrikPN/scigym#2]
Currently environment specific dependencies are included as extra dependencies, which are not automatically installed with installation of the scigym package. 

Would it not be preferable to include all environment specific dependencies as core dependencies of the scigym package itself, so that installation of the scigym package allows one to use all packaged environments with out needing to install additional (environment specific) dependencies first?

**Comment by HendrikPN** [comment]
In principle I agree. But if the package grows, we might want to reconsider. We don't want a too long list of dependencies that are installed with the library. But for now, that might be fine. Maybe we should however include them in a `requirements.txt` and install them from there. There are even dependency managers like `pipreqs` or `pipdeptree`. We should look into this.

**Comment by R-Sweke** [comment]
I thought about this, and looked into pipreqs and pipdeptree, and I have two suggestions:

The first suggestion would be to have _two_ requirements files - `requirements_minimal.txt` and `requirements_full.txt` - The minimal requirements file contains details of dependencies needed for a minimal install (no environment specific dependencies), and the full requirements file contains the dependencies needed for all environments, i.e. for a full install. From my perspective the main problem with a minimal install is that the unit tests would fail, and so my suggestion would be to recommend the full installation, but provide the minimal installation requirements file in case someone wants this for some reason. We could also structure the full installation requirements file in such a way that makes it easy to comment out the dependencies of a specific environment, and this would allow for control over the installation if someone wants only particular environments?

Another simpler option would be to only have one requirements file, with all dependencies for all environments, but then be explicit in the readme that the dependencies for any unwanted environments can be commented out in the requirements file. This would make the default installation a full installation, which would then pass all the unit tests.

I think my preference would be for the second option?

**Comment by HendrikPN** [comment]
Hey Ryan!
Thanks for your thoughts! One other option would be to have an requirements file for test purposes only. Then, we can have the requirements.txt contain the minimum install. Currently, the .Travis.yml explicitly installs "all" requirements.

Also, we can suggest in the README a way to install specific extra requirements. See this answer: https://stackoverflow.com/a/18879288

I think my preferred option is to specify a minimum install for 'pip install --user -e.' but supply a requirements.txt with a full install, which is used for testing by e.g. travis. In addition, we can add a comment to the README as in the above link.
My argument for this approach is to have a low weight package to begin with but leave it to the user to add requirements if need be. Currently, it doesn't make a difference but once we have 10 environments which have additional requirements, we don't want to have a user install all packages. If you think about it, Tensorflow  is a big package, then later we also add pytorch for one environment, and another big one, and another.... We need to contain it.

Do you agree?

Cheers,
Hendrik



Outlook für iOS<https://aka.ms/o0ukef> beziehen



On Sun, Aug 25, 2019 at 12:07 PM +0200, "Ryan Sweke" <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought about this, and looked into pipreqs and pipdeptree, and I have two suggestions:

The first suggestion would be to have two requirements files - requirements_minimal.txt and requirements_full.txt - The minimal requirements file contains details of dependencies needed for a minimal install (no environment specific dependencies), and the full requirements file contains the dependencies needed for all environments, i.e. for a full install. From my perspective the main problem with a minimal install is that the unit tests would fail, and so my suggestion would be to recommend the full installation, but provide the minimal installation requirements file in case someone wants this for some reason. We could also structure the full installation requirements file in such a way that makes it easy to comment out the dependencies of a specific environment, and this would allow for control over the installation if someone wants only particular environments?

Another simpler option would be to only have one requirements file, with all dependencies for all environments, but then be explicit in the readme that the dependencies for any unwanted environments can be commented out in the requirements file. This would make the default installation a full installation, which would then pass all the unit tests.

I think my preference would be for the second option?

**Comment by HendrikPN** [comment]
Thanks for your thoughts! Those are great ideas! 
To add one other option: We could have an requirements file for test purposes. Then, we can have the `requirements.txt` contain the minimum install. Currently, the `.travis.yml` explicitly installs all requirements.

Also, we can suggest in the `README` a way to install specific extra requirements. See this answer: https://stackoverflow.com/a/18879288

I think my preferred option is to specify a minimum install for `pip install --user -e.` but supply a `requirements.txt` with a full install, which is used for testing by e.g. travis. In addition, we can add a comment to the `README` as in the above link.
My argument for this approach is to have a low weight package to begin with but leave it to the user to add requirements if need be. Currently, it doesn't make a difference but once we have 10 environments which have additional requirements, we don't want to have a user install all packages. If you think about it, `tensorflow` is already a big package, then later we might also add `pytorch` for one environment. If this continues, we need a way to contain it.

Do you agree?

**Comment by R-Sweke** [comment]
Hey,

Ok, I like this suggestion! In essence, we make the minimal install default, but give very clear instructions in the readme of how to install extra environment specific dependencies  - i.e. via

 `pip install -e .[specific_environment]`

Where the dependencies of `specific_environment` are in the `extras` dictionary in `setup.py`.

If I understand correctly, then the way we have the `setup.py` file structured now is perfect, and the only thing we need to do is provide a `requirements_full.txt` file (via `pip freeze` for example) which can be used for a full install. This full install file can be used (a) for testing, or (b) for getting the full library without having to install all environment specific dependencies one by one (which might actually be a route that many people choose).

If we agree then I can make these changes and edit the readme to give instructions on the different installation options...

**Comment by HendrikPN** [comment]
Awesome, thanks a lot! 
Maybe, let's also make a section in the `README` where all the dependencies for all environments are listed. It could come somewhere at the end of the `README` and the section could be linked wherever we explain the minimum install.

Since we only have one `requirements.txt` file, maybe we don't need the `full` suffix.  
That's all my comments at this point, so feel free to go ahead. And thanks for doing this :)

**Comment by R-Sweke** [comment]
Great, this is now resolved via pull request #11.
