### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by HendrikPN** [HendrikPN/scigym#3]
We should add unittests to the repo, and require all environments to be covered.

For instance, we should test that `env.step(action)` and `env.reset()` retrieve elements which are in line with env.observation_space given an action from env.action_space. Also, we should test `isinstance(env.observation_space, scigym.Box)` and `isinstance(env.action_space_space, scigym.Discrete)`.

Any more ideas for tests, @R-Sweke ?

**Comment by R-Sweke** [comment]
I agree that there should definitely be unittests. The basic ones that you suggested make sense (a minor point though - environments can have observation spaces other than boxes, and so a better test might be something like `isinstance(env.observation_space, scigym.Space)`).

These tests cover some very basic potential issues, although I think that ideally we would also like to include testing of the actual functionality of the environment - i.e. perhaps we should require that contributors of environments provide us with one or two "test episodes" (i.e. a fixed sequence of steps/actions on a reference or seeded environment state) that we can build into a unit test of the scigym package?

**Comment by HendrikPN** [comment]
Good idea! It should also be mentioned in the `CONTRIBUTING.md` that we require tests of the form specified by you and I above.
We can follow `openai/gym` in this regard: https://github.com/openai/gym/tree/master/gym/envs/tests

**Comment by R-Sweke** [comment]
Perfect, will incorporate this into the pull request #1!
