### ISSUE TITLE
Install requires with versions

### ISSUE THREAD

**Issue by HendrikPN** [HendrikPN/scigym#5]
We should add `install_requires = ['gym==0.11.0']`. In particular, since new version might cause errors as in the `from gym.core import Space` from a previous version.

**Comment by R-Sweke** [comment]
This has been included in commit  [e0b0f91](/HendrikPN/scigym/pull/1/commits/e0b0f91708ea6e269e39a9ffffee4a26f06f0af3) of pull request #1.

**Comment by HendrikPN** [comment]
PR #1 closes this issue
